name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Label Pull Request
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          config: |
            labels:
              - name: "bug"
                path:
                  - "src/**/*.js"

              - name: "feature"
                path:
                  - "src/**/*.jsx"
                  - "src/**/*.ts"
                  - "src/**/*.tsx"

              - name: "documentation"
                path:
                  - "docs/**/*"
                  - "README.md"

              - name: "enhancement"
                path:
                  - "src/**/*.css"
                  - "src/**/*.scss"
                  - "src/**/*.less"
